# Generated by Django 3.1.3 on 2020-11-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(default=1223, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
