# Generated by Django 3.1.3 on 2020-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201109_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizparticipant',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
